<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ekumi" nsURI="http://fr.kazejiyu.io/ekumi" nsPrefix="ekumi">
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true">
    <eOperations name="run"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingFlows" upperBound="-1"
        eType="#//DataFlow" containment="true" eOpposite="#//DataFlow/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingFlows" upperBound="-1"
        eType="#//DataFlow" eOpposite="#//DataFlow/destination"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Data" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Data" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successors" upperBound="-1"
        eType="#//Activity" eOpposite="#//Activity/predecessor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" eType="#//Activity"
        eOpposite="#//Activity/successors"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//Status"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Workflow" abstract="true" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//Workflow"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleInstances" eSuperTypes="#//Workflow"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelSplit" eSuperTypes="#//Workflow"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Activity"
        eOpposite="#//Activity/outgoingFlows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//Activity" eOpposite="#//Activity/incomingFlows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//Data"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredLoop" eSuperTypes="#//Workflow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test" lowerBound="1" eType="#//TestableScript"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestableScript" eSuperTypes="#//Script">
    <eOperations name="check" eType="#//TestResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="IDLE"/>
    <eLiterals name="RUNNING" value="1"/>
    <eLiterals name="SUCCEEDED" value="2"/>
    <eLiterals name="FAILED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunnableScript" eSuperTypes="#//Script">
    <eOperations name="run"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptableTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="script" eType="#//RunnableScript"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Script" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestResult">
    <eLiterals name="FULFILLED"/>
    <eLiterals name="UNSATISFIED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ScriptingLanguage" instanceClassName="fr.kazejiyu.ekumi.core.languages.ScriptingLanguage"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DataType" instanceClassName="fr.kazejiyu.ekumi.core.datatypes.DataType"/>
</ecore:EPackage>
