<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spec" nsURI="http://fr.kazejiyu.io/ekumi/spec" nsPrefix="spec">
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="successors" upperBound="-1"
        eType="#//Activity" volatile="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="join" eType="#//Join" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Join" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartJoin" eSuperTypes="#//Join"/>
  <eClassifiers xsi:type="ecore:EClass" name="SplitJoin" eSuperTypes="#//Join"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleJoin" eSuperTypes="#//Join"/>
  <eClassifiers xsi:type="ecore:EClass" name="RepeatJoin" eSuperTypes="#//Join"/>
  <eClassifiers xsi:type="ecore:EClass" name="Workflow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//StartJoin"
        volatile="true" derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subWorkflow" eType="#//Workflow"
        containment="true" eOpposite="#//Workflow/parentWorkflow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentWorkflow" eType="#//Workflow"
        eOpposite="#//Workflow/subWorkflow"/>
  </eClassifiers>
</ecore:EPackage>
