package fr.kazejiyu.ekumi.model.workflow.provider;

/**
 * A decorator that forwards any method call to the item provider generated by EMF.
 * 
 * @author Emmanuel CHEBBI
 */
public class ForwardingItemProviderAdapterDecorator extends ItemProviderAdapterDecorator {

	public ForwardingItemProviderAdapterDecorator(EkumiDecoratorAdapterFactory adapterFactory) {
		super(adapterFactory);
	}
	
}